# Use https://travis-ci.org/ for automatic testing

# speed up testing https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# This is a java project
language: java

script: mvn test -B

jdk:
  - oraclejdk8
  - oraclejdk9
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: test_builds/  # or remove this line to upload from root of repo
  file: LagMonitor.jar
  github_token: e9a471b8694e3b8057e9f0a02d2984e1ee9e5db4 # Set in travis-ci.org dashboard
  api_key: e9a471b8694e3b8057e9f0a02d2984e1ee9e5db4
  on:
    branch: master
